# NUMPY HANDS-ON PRACTICE

## Exercise 1: Meet your first NumPy Arrays

### Task 1: Import NumPy

In [5]:
import numpy as np

# The cell runs without an error because Numpy is already installed in the environment.

### Task 2: Create your array

In [7]:
temperatures = [27.5, 19.0, 28.5]

temperatures_array = np.array(temperatures)

print(f"Temperature array: {temperatures_array}")

Temperature array: [27.5 19.  28.5]


### Task 3 - Inspect the data type

In [8]:
print("Data type: ", temperatures_array.dtype)

Data type:  float64


### Task 4 - Create a 2D array

In [9]:
weather_data = [
    [27.5, 28.0, 29.5],
    [28.0, 29.0, 30.0]
]

weather_data_array = np.array(weather_data)

print(f"Weather data array: {weather_data_array}")

Weather data array: [[27.5 28.  29.5]
 [28.  29.  30. ]]


Challenge Answers:

1. It is a 2D array.
2. It is a matrix.
3. It has 2 rows.
4. Each row has 3 values.

## Exercise 2 - Python lists vs NumPy arrays

### Task 1 - Try it with Python Lists

In [12]:
sales_timothy = [10, 15, 20]
sales_brenda = [5, 10, 15]

print(sales_timothy + sales_brenda)

[10, 15, 20, 5, 10, 15]


1. Python did not produce [15, 25, 35]
2. From the result above, Python concatenated the two lists.
3. This happened because the + operator combines lists by concatenating them instead of performing element-by-element numerical addition.

### Task 2 - Convert them to NumPy arrays

In [13]:
sales_timothy_array = np.array(sales_timothy)
sales_brenda_array = np.array(sales_brenda)

print(f"Combined Sales: {sales_timothy_array + sales_brenda_array}")

Combined Sales: [15 25 35]


### Task 3 - Compare the results

| Approach | Result |
| --- | --- |
| Python lists | [10, 15, 20, 5, 10, 15]
|
| NumPy arrays | [15, 25, 35]

Numpy is useful because it allows numerical operations to be performed element-by-element. This makes it convinient to compare and calculate corresponding values in numerical datasets.

### Challenge

In [14]:
online_sales = np.array([10, 44, 21, 13, 22])
store_sales = np.array([12, 33, 13, 34, 11])

print("Combined sales for each day: ", online_sales + store_sales)
print("Difference between online and store sales: ", online_sales - store_sales)

Combined sales for each day:  [22 77 34 47 33]
Difference between online and store sales:  [ -2  11   8 -21  11]


## Exercise 3

## Mini Project - Weather Data Quick Analysis

# 1. Project Title
### Weather Temperaure Analysis with NumPy

# 2. Project Introduction

This project uses NumPy to analyse temperature data recorded by a weather-monitoring station.

The station recorded daily temperatures for one week. The aim is to convert the raw numerical data into NumPy arrays and perform basic numerical analysis.

# 3. Import NumPy

In [16]:
import numpy as np

# 4. Dataset

### Weekly Temperature Dataset

The weather station recorded the following temperatures for one week:

[27.5, 29.0, 30.5, 28.0, 31.0, 32.5, 30.0]

In [17]:
temperatures = [27.5, 29.0, 30.5, 28.0, 31.0, 32.5, 30.0]

print(temperatures)

[27.5, 29.0, 30.5, 28.0, 31.0, 32.5, 30.0]


### Target Temperature Dataset

The target temperatures for the seven days are:

[28.0, 28.0, 29.0, 28.0, 30.0, 30.0, 29.0]

In [18]:
target = [28.0, 28.0, 29.0, 28.0, 30.0, 30.0, 29.0]

print(target)

[28.0, 28.0, 29.0, 28.0, 30.0, 30.0, 29.0]


### Location Datasets

The three weather-monitoring locations are:

Lagos: [27.5, 29.0, 30.5, 28.0, 31.0]

Abuja: [25.0, 28.0, 29.5, 30.0, 32.0]

Ibadan: [26.5, 28.5, 29.0, 27.5, 30.5]

In [19]:
lagos = [27.5, 29.0, 30.5, 28.0, 31.0]
abuja = [25.0, 28.0, 29.5, 30.0, 32.0]
ibadan = [26.5, 28.5, 29.0, 27.5, 30.5]

print(f"Lagos: {lagos}")
print(f"Abuja: {abuja}")
print(f"Ibadan: {ibadan}")

Lagos: [27.5, 29.0, 30.5, 28.0, 31.0]
Abuja: [25.0, 28.0, 29.5, 30.0, 32.0]
Ibadan: [26.5, 28.5, 29.0, 27.5, 30.5]


# 5. Convert Data to NumPy arrays

In [20]:
temperatures_array = np.array(temperatures)

print("Temperatures Array: ", temperatures_array)

Temperatures Array:  [27.5 29.  30.5 28.  31.  32.5 30. ]


In [21]:
target_array = np.array(target)

print(f"Target Array: {target_array}")

Target Array: [28. 28. 29. 28. 30. 30. 29.]


In [22]:
lagos_array = np.array(lagos)
abuja_array = np.array(abuja)
ibadan_array = np.array(ibadan)

print(f"Lagos: {lagos_array}")
print(f"Abuja: {abuja_array}")
print(f"Ibadan: {ibadan_array}")

Lagos: [27.5 29.  30.5 28.  31. ]
Abuja: [25.  28.  29.5 30.  32. ]
Ibadan: [26.5 28.5 29.  27.5 30.5]


# 6. Array Inspection

In [24]:
print("Data Type: ", temperatures_array.dtype)

Data Type:  float64


# 7. Numerical Operations

### Task A - Temperature Difference

In [27]:
print("Temperature Difference: ", temperatures_array - target_array)

Temperature Difference:  [-0.5  1.   1.5  0.   1.   2.5  1. ]


### Task B - Temperature Increase

In [28]:
print("Temperature Increase: ", temperatures_array + 2)

Temperature Increase:  [29.5 31.  32.5 30.  33.  34.5 32. ]


### Think like an Analyst

# 8. Lagos vs Abuja Comparison

In [29]:
import numpy as np

lagos = [27.5, 29.0, 30.5, 28.0, 31.0]
abuja = [25.0, 28.0, 29.5, 30.0, 32.0]
ibadan = [26.5, 28.5, 29.0, 27.5, 30.5]

lagos_array = np.array(lagos)
abuja_array = np.array(abuja)
ibadan_array = np.array(ibadan)

print(f"Lagos Array: {lagos_array}")
print(f"Abuja Array: {abuja_array}")
print(f"Ibadan Array: {ibadan_array}")

Lagos Array: [27.5 29.  30.5 28.  31. ]
Abuja Array: [25.  28.  29.5 30.  32. ]
Ibadan Array: [26.5 28.5 29.  27.5 30.5]


### Challenge 1
What location recorded the highest temperature on each day?

In [30]:
highest_temperature_each_day = np.maximum(lagos_array, abuja_array)

highest_temperature_each_day = np.maximum(highest_temperature_each_day, abuja_array)

print(f"Highest Temperature Each Day: {highest_temperature_each_day}")

Highest Temperature Each Day: [27.5 29.  30.5 30.  32. ]


### Challenge 2
Create a calculation that increases every recorded temperature by 1

In [31]:
lagos_temperature_increase = lagos_array + 1
abuja_temperature_increase = abuja_array + 1
ibadan_temperature_increase = ibadan_array + 1

print(f"Lagos: {lagos_temperature_increase}")
print(f"Abuja: {abuja_temperature_increase}")
print(f"Ibadan: {ibadan_temperature_increase}")

Lagos: [28.5 30.  31.5 29.  32. ]
Abuja: [26.  29.  30.5 31.  33. ]
Ibadan: [27.5 29.5 30.  28.5 31.5]


### Challenge 4
Explain why NumPy becomes increasingly useful as the amount of numerical data grows

Answer:


NumPy becomes increasingly useful because it allows us to store many numerical values in arrays and perform calculations on them efficiently.

Instead of calculating each value seperately, NumPy allows us to perform operations on an entire array element by element.

This makes it easier to work with larger amounts of numerical data.

## Bonus Challenge

### My predictions

x + y = [3, 7, 1]

x - y = [1, 1, 1]

x * y = [2, 12, 30]

In [32]:
x = np.array([2, 4, 6])
y = np.array([1, 3, 5])

print(x + y)
print(x - y)
print(x * y)

[ 3  7 11]
[1 1 1]
[ 2 12 30]


### Comparison

What I expected:

x + y = [3, 7, 11]

x - y = [1, 1, 1]

x * y = [2, 12, 30]

What Python produced:

x + y = [3, 7, 11]

x - y = [1, 1, 1]

x * y = [2, 12, 30]

What I learned: 

NumPy performs arithmetic operations element by element when working with NumPy arrays.

# 9. Findings

# 10. Conclusion

This project demonstrated how Numpy can be used to work with numerical temperature data.

The temperature data was converted from Python list into NumPy arrays. NumPy was then used to perform numerical calculations, compare temperatures with target values, and compare temperstures between different locations.

This project shows how NumPy makes numerical operations easier by allowing calculations to be performed element by element.